// Code generated by ent, DO NOT EDIT.

package xrayconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/tools4net/ezfw/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// LogIsNil applies the IsNil predicate on the "log" field.
func LogIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldLog))
}

// LogNotNil applies the NotNil predicate on the "log" field.
func LogNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldLog))
}

// APIIsNil applies the IsNil predicate on the "api" field.
func APIIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldAPI))
}

// APINotNil applies the NotNil predicate on the "api" field.
func APINotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldAPI))
}

// DNSIsNil applies the IsNil predicate on the "dns" field.
func DNSIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldDNS))
}

// DNSNotNil applies the NotNil predicate on the "dns" field.
func DNSNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldDNS))
}

// RoutingIsNil applies the IsNil predicate on the "routing" field.
func RoutingIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldRouting))
}

// RoutingNotNil applies the NotNil predicate on the "routing" field.
func RoutingNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldRouting))
}

// PolicyIsNil applies the IsNil predicate on the "policy" field.
func PolicyIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldPolicy))
}

// PolicyNotNil applies the NotNil predicate on the "policy" field.
func PolicyNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldPolicy))
}

// InboundsIsNil applies the IsNil predicate on the "inbounds" field.
func InboundsIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldInbounds))
}

// InboundsNotNil applies the NotNil predicate on the "inbounds" field.
func InboundsNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldInbounds))
}

// OutboundsIsNil applies the IsNil predicate on the "outbounds" field.
func OutboundsIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldOutbounds))
}

// OutboundsNotNil applies the NotNil predicate on the "outbounds" field.
func OutboundsNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldOutbounds))
}

// TransportIsNil applies the IsNil predicate on the "transport" field.
func TransportIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldTransport))
}

// TransportNotNil applies the NotNil predicate on the "transport" field.
func TransportNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldTransport))
}

// StatsIsNil applies the IsNil predicate on the "stats" field.
func StatsIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldStats))
}

// StatsNotNil applies the NotNil predicate on the "stats" field.
func StatsNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldStats))
}

// ReverseIsNil applies the IsNil predicate on the "reverse" field.
func ReverseIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldReverse))
}

// ReverseNotNil applies the NotNil predicate on the "reverse" field.
func ReverseNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldReverse))
}

// FakednsIsNil applies the IsNil predicate on the "fakedns" field.
func FakednsIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldFakedns))
}

// FakednsNotNil applies the NotNil predicate on the "fakedns" field.
func FakednsNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldFakedns))
}

// MetricsIsNil applies the IsNil predicate on the "metrics" field.
func MetricsIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldMetrics))
}

// MetricsNotNil applies the NotNil predicate on the "metrics" field.
func MetricsNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldMetrics))
}

// ObservatoryIsNil applies the IsNil predicate on the "observatory" field.
func ObservatoryIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldObservatory))
}

// ObservatoryNotNil applies the NotNil predicate on the "observatory" field.
func ObservatoryNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldObservatory))
}

// BurstObservatoryIsNil applies the IsNil predicate on the "burst_observatory" field.
func BurstObservatoryIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldBurstObservatory))
}

// BurstObservatoryNotNil applies the NotNil predicate on the "burst_observatory" field.
func BurstObservatoryNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldBurstObservatory))
}

// ServicesIsNil applies the IsNil predicate on the "services" field.
func ServicesIsNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldIsNull(FieldServices))
}

// ServicesNotNil applies the NotNil predicate on the "services" field.
func ServicesNotNil() predicate.XrayConfig {
	return predicate.XrayConfig(sql.FieldNotNull(FieldServices))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.XrayConfig) predicate.XrayConfig {
	return predicate.XrayConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.XrayConfig) predicate.XrayConfig {
	return predicate.XrayConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.XrayConfig) predicate.XrayConfig {
	return predicate.XrayConfig(sql.NotPredicates(p))
}
