// Code generated by ent, DO NOT EDIT.

package xrayconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the xrayconfig type in the database.
	Label = "xray_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLog holds the string denoting the log field in the database.
	FieldLog = "log"
	// FieldAPI holds the string denoting the api field in the database.
	FieldAPI = "api"
	// FieldDNS holds the string denoting the dns field in the database.
	FieldDNS = "dns"
	// FieldRouting holds the string denoting the routing field in the database.
	FieldRouting = "routing"
	// FieldPolicy holds the string denoting the policy field in the database.
	FieldPolicy = "policy"
	// FieldInbounds holds the string denoting the inbounds field in the database.
	FieldInbounds = "inbounds"
	// FieldOutbounds holds the string denoting the outbounds field in the database.
	FieldOutbounds = "outbounds"
	// FieldTransport holds the string denoting the transport field in the database.
	FieldTransport = "transport"
	// FieldStats holds the string denoting the stats field in the database.
	FieldStats = "stats"
	// FieldReverse holds the string denoting the reverse field in the database.
	FieldReverse = "reverse"
	// FieldFakedns holds the string denoting the fakedns field in the database.
	FieldFakedns = "fakedns"
	// FieldMetrics holds the string denoting the metrics field in the database.
	FieldMetrics = "metrics"
	// FieldObservatory holds the string denoting the observatory field in the database.
	FieldObservatory = "observatory"
	// FieldBurstObservatory holds the string denoting the burst_observatory field in the database.
	FieldBurstObservatory = "burst_observatory"
	// FieldServices holds the string denoting the services field in the database.
	FieldServices = "services"
	// Table holds the table name of the xrayconfig in the database.
	Table = "xray_configs"
)

// Columns holds all SQL columns for xrayconfig fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLog,
	FieldAPI,
	FieldDNS,
	FieldRouting,
	FieldPolicy,
	FieldInbounds,
	FieldOutbounds,
	FieldTransport,
	FieldStats,
	FieldReverse,
	FieldFakedns,
	FieldMetrics,
	FieldObservatory,
	FieldBurstObservatory,
	FieldServices,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the XrayConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
