// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tools4net/ezfw/backend/ent/haproxyconfig"
	"github.com/tools4net/ezfw/backend/ent/predicate"
)

// HAProxyConfigQuery is the builder for querying HAProxyConfig entities.
type HAProxyConfigQuery struct {
	config
	ctx        *QueryContext
	order      []haproxyconfig.OrderOption
	inters     []Interceptor
	predicates []predicate.HAProxyConfig
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the HAProxyConfigQuery builder.
func (hpcq *HAProxyConfigQuery) Where(ps ...predicate.HAProxyConfig) *HAProxyConfigQuery {
	hpcq.predicates = append(hpcq.predicates, ps...)
	return hpcq
}

// Limit the number of records to be returned by this query.
func (hpcq *HAProxyConfigQuery) Limit(limit int) *HAProxyConfigQuery {
	hpcq.ctx.Limit = &limit
	return hpcq
}

// Offset to start from.
func (hpcq *HAProxyConfigQuery) Offset(offset int) *HAProxyConfigQuery {
	hpcq.ctx.Offset = &offset
	return hpcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (hpcq *HAProxyConfigQuery) Unique(unique bool) *HAProxyConfigQuery {
	hpcq.ctx.Unique = &unique
	return hpcq
}

// Order specifies how the records should be ordered.
func (hpcq *HAProxyConfigQuery) Order(o ...haproxyconfig.OrderOption) *HAProxyConfigQuery {
	hpcq.order = append(hpcq.order, o...)
	return hpcq
}

// First returns the first HAProxyConfig entity from the query.
// Returns a *NotFoundError when no HAProxyConfig was found.
func (hpcq *HAProxyConfigQuery) First(ctx context.Context) (*HAProxyConfig, error) {
	nodes, err := hpcq.Limit(1).All(setContextOp(ctx, hpcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{haproxyconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) FirstX(ctx context.Context) *HAProxyConfig {
	node, err := hpcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first HAProxyConfig ID from the query.
// Returns a *NotFoundError when no HAProxyConfig ID was found.
func (hpcq *HAProxyConfigQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hpcq.Limit(1).IDs(setContextOp(ctx, hpcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{haproxyconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) FirstIDX(ctx context.Context) string {
	id, err := hpcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single HAProxyConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one HAProxyConfig entity is found.
// Returns a *NotFoundError when no HAProxyConfig entities are found.
func (hpcq *HAProxyConfigQuery) Only(ctx context.Context) (*HAProxyConfig, error) {
	nodes, err := hpcq.Limit(2).All(setContextOp(ctx, hpcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{haproxyconfig.Label}
	default:
		return nil, &NotSingularError{haproxyconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) OnlyX(ctx context.Context) *HAProxyConfig {
	node, err := hpcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only HAProxyConfig ID in the query.
// Returns a *NotSingularError when more than one HAProxyConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (hpcq *HAProxyConfigQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = hpcq.Limit(2).IDs(setContextOp(ctx, hpcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{haproxyconfig.Label}
	default:
		err = &NotSingularError{haproxyconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) OnlyIDX(ctx context.Context) string {
	id, err := hpcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of HAProxyConfigs.
func (hpcq *HAProxyConfigQuery) All(ctx context.Context) ([]*HAProxyConfig, error) {
	ctx = setContextOp(ctx, hpcq.ctx, ent.OpQueryAll)
	if err := hpcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*HAProxyConfig, *HAProxyConfigQuery]()
	return withInterceptors[[]*HAProxyConfig](ctx, hpcq, qr, hpcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) AllX(ctx context.Context) []*HAProxyConfig {
	nodes, err := hpcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of HAProxyConfig IDs.
func (hpcq *HAProxyConfigQuery) IDs(ctx context.Context) (ids []string, err error) {
	if hpcq.ctx.Unique == nil && hpcq.path != nil {
		hpcq.Unique(true)
	}
	ctx = setContextOp(ctx, hpcq.ctx, ent.OpQueryIDs)
	if err = hpcq.Select(haproxyconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) IDsX(ctx context.Context) []string {
	ids, err := hpcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (hpcq *HAProxyConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, hpcq.ctx, ent.OpQueryCount)
	if err := hpcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, hpcq, querierCount[*HAProxyConfigQuery](), hpcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) CountX(ctx context.Context) int {
	count, err := hpcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (hpcq *HAProxyConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, hpcq.ctx, ent.OpQueryExist)
	switch _, err := hpcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (hpcq *HAProxyConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := hpcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the HAProxyConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (hpcq *HAProxyConfigQuery) Clone() *HAProxyConfigQuery {
	if hpcq == nil {
		return nil
	}
	return &HAProxyConfigQuery{
		config:     hpcq.config,
		ctx:        hpcq.ctx.Clone(),
		order:      append([]haproxyconfig.OrderOption{}, hpcq.order...),
		inters:     append([]Interceptor{}, hpcq.inters...),
		predicates: append([]predicate.HAProxyConfig{}, hpcq.predicates...),
		// clone intermediate query.
		sql:  hpcq.sql.Clone(),
		path: hpcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.HAProxyConfig.Query().
//		GroupBy(haproxyconfig.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (hpcq *HAProxyConfigQuery) GroupBy(field string, fields ...string) *HAProxyConfigGroupBy {
	hpcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &HAProxyConfigGroupBy{build: hpcq}
	grbuild.flds = &hpcq.ctx.Fields
	grbuild.label = haproxyconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.HAProxyConfig.Query().
//		Select(haproxyconfig.FieldName).
//		Scan(ctx, &v)
func (hpcq *HAProxyConfigQuery) Select(fields ...string) *HAProxyConfigSelect {
	hpcq.ctx.Fields = append(hpcq.ctx.Fields, fields...)
	sbuild := &HAProxyConfigSelect{HAProxyConfigQuery: hpcq}
	sbuild.label = haproxyconfig.Label
	sbuild.flds, sbuild.scan = &hpcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a HAProxyConfigSelect configured with the given aggregations.
func (hpcq *HAProxyConfigQuery) Aggregate(fns ...AggregateFunc) *HAProxyConfigSelect {
	return hpcq.Select().Aggregate(fns...)
}

func (hpcq *HAProxyConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range hpcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, hpcq); err != nil {
				return err
			}
		}
	}
	for _, f := range hpcq.ctx.Fields {
		if !haproxyconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if hpcq.path != nil {
		prev, err := hpcq.path(ctx)
		if err != nil {
			return err
		}
		hpcq.sql = prev
	}
	return nil
}

func (hpcq *HAProxyConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*HAProxyConfig, error) {
	var (
		nodes = []*HAProxyConfig{}
		_spec = hpcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*HAProxyConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &HAProxyConfig{config: hpcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, hpcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (hpcq *HAProxyConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := hpcq.querySpec()
	_spec.Node.Columns = hpcq.ctx.Fields
	if len(hpcq.ctx.Fields) > 0 {
		_spec.Unique = hpcq.ctx.Unique != nil && *hpcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, hpcq.driver, _spec)
}

func (hpcq *HAProxyConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(haproxyconfig.Table, haproxyconfig.Columns, sqlgraph.NewFieldSpec(haproxyconfig.FieldID, field.TypeString))
	_spec.From = hpcq.sql
	if unique := hpcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if hpcq.path != nil {
		_spec.Unique = true
	}
	if fields := hpcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, haproxyconfig.FieldID)
		for i := range fields {
			if fields[i] != haproxyconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := hpcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := hpcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := hpcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := hpcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (hpcq *HAProxyConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(hpcq.driver.Dialect())
	t1 := builder.Table(haproxyconfig.Table)
	columns := hpcq.ctx.Fields
	if len(columns) == 0 {
		columns = haproxyconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if hpcq.sql != nil {
		selector = hpcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if hpcq.ctx.Unique != nil && *hpcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range hpcq.predicates {
		p(selector)
	}
	for _, p := range hpcq.order {
		p(selector)
	}
	if offset := hpcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := hpcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// HAProxyConfigGroupBy is the group-by builder for HAProxyConfig entities.
type HAProxyConfigGroupBy struct {
	selector
	build *HAProxyConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (hpcgb *HAProxyConfigGroupBy) Aggregate(fns ...AggregateFunc) *HAProxyConfigGroupBy {
	hpcgb.fns = append(hpcgb.fns, fns...)
	return hpcgb
}

// Scan applies the selector query and scans the result into the given value.
func (hpcgb *HAProxyConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hpcgb.build.ctx, ent.OpQueryGroupBy)
	if err := hpcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HAProxyConfigQuery, *HAProxyConfigGroupBy](ctx, hpcgb.build, hpcgb, hpcgb.build.inters, v)
}

func (hpcgb *HAProxyConfigGroupBy) sqlScan(ctx context.Context, root *HAProxyConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(hpcgb.fns))
	for _, fn := range hpcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*hpcgb.flds)+len(hpcgb.fns))
		for _, f := range *hpcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*hpcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hpcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// HAProxyConfigSelect is the builder for selecting fields of HAProxyConfig entities.
type HAProxyConfigSelect struct {
	*HAProxyConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (hpcs *HAProxyConfigSelect) Aggregate(fns ...AggregateFunc) *HAProxyConfigSelect {
	hpcs.fns = append(hpcs.fns, fns...)
	return hpcs
}

// Scan applies the selector query and scans the result into the given value.
func (hpcs *HAProxyConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, hpcs.ctx, ent.OpQuerySelect)
	if err := hpcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*HAProxyConfigQuery, *HAProxyConfigSelect](ctx, hpcs.HAProxyConfigQuery, hpcs, hpcs.inters, v)
}

func (hpcs *HAProxyConfigSelect) sqlScan(ctx context.Context, root *HAProxyConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(hpcs.fns))
	for _, fn := range hpcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*hpcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := hpcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
