// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tools4net/ezfw/backend/ent/predicate"
	"github.com/tools4net/ezfw/backend/ent/serviceinstance"
)

// ServiceInstanceDelete is the builder for deleting a ServiceInstance entity.
type ServiceInstanceDelete struct {
	config
	hooks    []Hook
	mutation *ServiceInstanceMutation
}

// Where appends a list predicates to the ServiceInstanceDelete builder.
func (sid *ServiceInstanceDelete) Where(ps ...predicate.ServiceInstance) *ServiceInstanceDelete {
	sid.mutation.Where(ps...)
	return sid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sid *ServiceInstanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sid.sqlExec, sid.mutation, sid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sid *ServiceInstanceDelete) ExecX(ctx context.Context) int {
	n, err := sid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sid *ServiceInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(serviceinstance.Table, sqlgraph.NewFieldSpec(serviceinstance.FieldID, field.TypeString))
	if ps := sid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sid.mutation.done = true
	return affected, err
}

// ServiceInstanceDeleteOne is the builder for deleting a single ServiceInstance entity.
type ServiceInstanceDeleteOne struct {
	sid *ServiceInstanceDelete
}

// Where appends a list predicates to the ServiceInstanceDelete builder.
func (sido *ServiceInstanceDeleteOne) Where(ps ...predicate.ServiceInstance) *ServiceInstanceDeleteOne {
	sido.sid.mutation.Where(ps...)
	return sido
}

// Exec executes the deletion query.
func (sido *ServiceInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := sido.sid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serviceinstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sido *ServiceInstanceDeleteOne) ExecX(ctx context.Context) {
	if err := sido.Exec(ctx); err != nil {
		panic(err)
	}
}
