// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tools4net/ezfw/backend/ent/predicate"
	"github.com/tools4net/ezfw/backend/ent/xrayconfig"
)

// XrayConfigDelete is the builder for deleting a XrayConfig entity.
type XrayConfigDelete struct {
	config
	hooks    []Hook
	mutation *XrayConfigMutation
}

// Where appends a list predicates to the XrayConfigDelete builder.
func (xcd *XrayConfigDelete) Where(ps ...predicate.XrayConfig) *XrayConfigDelete {
	xcd.mutation.Where(ps...)
	return xcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (xcd *XrayConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, xcd.sqlExec, xcd.mutation, xcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (xcd *XrayConfigDelete) ExecX(ctx context.Context) int {
	n, err := xcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (xcd *XrayConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(xrayconfig.Table, sqlgraph.NewFieldSpec(xrayconfig.FieldID, field.TypeString))
	if ps := xcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, xcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	xcd.mutation.done = true
	return affected, err
}

// XrayConfigDeleteOne is the builder for deleting a single XrayConfig entity.
type XrayConfigDeleteOne struct {
	xcd *XrayConfigDelete
}

// Where appends a list predicates to the XrayConfigDelete builder.
func (xcdo *XrayConfigDeleteOne) Where(ps ...predicate.XrayConfig) *XrayConfigDeleteOne {
	xcdo.xcd.mutation.Where(ps...)
	return xcdo
}

// Exec executes the deletion query.
func (xcdo *XrayConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := xcdo.xcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{xrayconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (xcdo *XrayConfigDeleteOne) ExecX(ctx context.Context) {
	if err := xcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
