// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AgentToken is the predicate function for agenttoken builders.
type AgentToken func(*sql.Selector)

// HAProxyConfig is the predicate function for haproxyconfig builders.
type HAProxyConfig func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// ServiceInstance is the predicate function for serviceinstance builders.
type ServiceInstance func(*sql.Selector)

// SingBoxConfig is the predicate function for singboxconfig builders.
type SingBoxConfig func(*sql.Selector)

// XrayConfig is the predicate function for xrayconfig builders.
type XrayConfig func(*sql.Selector)
